story1_app/urls.py
from django.urls import path
from . import views

app_name = 'story1_app'

urlpatterns = [
    path('', views.index, name='index'),
]

story4_app/urls.py
from django.urls import path
from . import views

app_name = "story4_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("random/", views.random, name="random")
]

story4_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("story4_app.urls")),
    path("story1_app/", include("story1_app.urls")),
]

story1_app/models.py
from django.db import models

# Create your models here.

story4_app/models.py
from django.db import models

# Create your models here.

story1_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        "type" : "story1_app"
    }
    return render(request, "story1_app/index.html", context)

story4_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        "type" : "index"
    }
    return render(request, "story4_app/index.html", context)

def random(request):
    context = {
        "type" : "random"
    }
    return render(request, "story4_app/random.html", context)

story1_app/templates/story1_app/index.html
{% extends "story4_app/base.html" %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- External CSS-->
    <link rel="stylesheet" href="{% static 'story1_app/style.css' %}">
    <title>Hadi Belajar PPW</title>

<div class="row height-with-nav">
    <center><h1> Story 1 PPW Hadi</h1>
    <figure>
        <img src="{% static 'story1_app/fotodiri.jpg' %}">
        <figcaption>
            Nama: Taufiq Hadi Pratama <br>
            NPM: 1906350856 <br>
            Angkatan: Maung 2019 <br>
            Mahasiswa di Fasilkom UI
        </figcaption>
        
    </figure> 

    <div class="describe">
        <p>
            Short Description: Seorang pemuda yang senang bermain game. Tampak selalu ceria 
            tetapi dalam hati kadang suram.
            Saya masuk Fasilkom UI karena merasa termotivasi oleh perkembangan teknologi yang sangat pesat. 
            Saya ingin bisa main biola dan piano, tetapi saat ini
            cukup dengan menikmati lagu-lagunya saja.
        </p>
    </div> </center>

    <div class="education-history column">
        <h3>Riwayat Pendidikan</h3>
        <table>
            <tr id="first-row-table">
                <th>Nama sekolah/institusi</th>
                <th>Tahun</th>
            </tr>
            <tr>
                <th>SDN Cikoko 03</th>
                <th>2007-2013</th>
            </tr>
            <tr>
                <th>SMPN 73 jakarta</th>
                <th>2013-2016</th>
            </tr>
            <tr>
                <th>SMAN 8 Jakarta</th>
                <th>2016-2019</th>
            </tr>
            <tr>
                <th>Universitas Indonesia</th>
                <th>2019-sekarang</th>
            </tr>
        </table>
    </div>
    
    <div class="social-media column">
        <h3>Kunjungi media sosial saya untuk tahu tentang saya lebih lanjut!</h3>
        <a href="https://www.facebook.com/taufiqhadi.pratama/">
            <img src="https://image.flaticon.com/icons/png/512/61/61045.png" class="sosmed">
        </a>
        <a href="https://www.instagram.com/_hadipratama768/">
            <img src="https://image.flaticon.com/icons/png/512/87/87390.png" class="sosmed">
        </a>
        <a href="https://www.linkedin.com/in/taufiq-hadi-pratama-21b3b4192/">
            <img src="https://image.flaticon.com/icons/png/512/61/61109.png" class="sosmed">
        </a>
        <a href="https://line.me/ti/p/r3BU2vFGwr">
            <img src="https://www.freepnglogos.com/uploads/line-logo-png-7.png" class="sosmed">
        </a>
    </div>

    <br>

    <div class="bonus">
    <h3>Bonus!!!!</h3>
        Arknights: Trigonometri#2978 <br>
        Honkai Impact 3 ID: 11445869
    </div>
</div>
{% endblock %}

story4_app/templates/story4_app/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
            crossorigin="anonymous">

        <!-- External CSS-->
        <link rel="stylesheet" href="{% static 'story4_app/css/style.css' %}">

        <!-- Needed font-->
        <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
        <title>Story4 Hadi</title>
    </head>
    <body>
        {% if type == "index" %}
        <nav class="navbar navbar-expand-lg navbar-light bg-navbar sticky-top">
            <img src="{% static 'story4_app/photos/icon.svg' %}" class="navbar-image">
            <a class="navbar-brand" href="#">PPW From Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="#">I am... <span class="sr-only">(current)</span></a>
                <a class="nav-link" href="#activities">Activities</a>
                <a class="nav-link" href="#contact">Find me at</a>
                <a class="nav-link" href="{% url 'story4_app:random' %}">Random</a>
                <a class="nav-link" href="{% url 'story1_app:index' %}">Story 1</a>
            </div>
            </div>
        </nav>
        {% elif type == "random" %}
        <nav class="navbar navbar-expand-lg navbar-light bg-navbar sticky-top">
            <img src="{% static 'story4_app/photos/icon.svg' %}" class="navbar-image">
            <a class="navbar-brand" href="#">PPW From Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="{% url 'story4_app:index' %}">I am... <span class="sr-only">(current)</span></a>
                <a class="nav-link" href="{% url 'story4_app:index' %}#activities">Activities</a>
                <a class="nav-link" href="{% url 'story4_app:index' %}#contact">Find me at</a>
                <a class="nav-link" href="#">Random</a>
                <a class="nav-link" href="{% url 'story1_app:index' %}">Story 1</a>
            </div>
            </div>
        </nav>
        {% elif type == "story1_app" %}
        <nav class="navbar navbar-expand-lg navbar-light bg-navbar sticky-top">
            <img src="{% static 'story4_app/photos/icon.svg' %}" class="navbar-image">
            <a class="navbar-brand" href="#">PPW From Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="{% url 'story4_app:index' %}">I am... <span class="sr-only">(current)</span></a>
                <a class="nav-link" href="{% url 'story4_app:index' %}#activities">Activities</a>
                <a class="nav-link" href="{% url 'story4_app:index' %}#contact">Find me at</a>
                <a class="nav-link" href="{% url 'story4_app:random' %}">Random</a>
                <a class="nav-link" href="#">Story 1</a>
            </div>
            </div>
        </nav>
        {% endif %}

        {% block content %}
        {% endblock %}


        <footer class="bg-navbar">
            <div class="text-center">Made with sincere by Taufiq Hadi Pratama, 2020</div>
        </footer>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    </body>
</html>

story4_app/templates/story4_app/index.html
{% extends "story4_app/base.html" %}
{% block content %}
{% load static %}
    <div class="container-fluid background" id="about">
    <div class="row height-with-nav">
        <div class="col-lg-6 col-sm-23 h-lg-100 d-flex align-items-center justify-content-center">
            <figure>
            <img src="{% static 'story4_app/photos/fotodiri.jpg' %}" class="img-fluid" alt="Responsive image">
            <center><figcaption >Foto saat <i>Social Project</i> PMB Fasilkom UI 2019</figcaption></center>
            </figure>
        </div>
        <div class="col-lg-6 col-sm-23 h-lg-100 p-3 d-flex flex-column align-items-center justify-content-center">
            <h2>Taufiq Hadi Pratama</h2>
            <h2>Fasilkom UI Angkatan 2019</h2>
            <h4>Seorang pemuda yang senang bermain game. Tampak selalu ceria tetapi dalam hati kadang suram.
                Saya ingin bisa main biola dan piano, tetapi saat ini
                cukup dengan menikmati lagu-lagunya saja.</h4>
        </div>
    </div>
    </div>

    <div class="container-fluid bg-activities" id="activities">
        <span class="custom-br bg-activities"></span>
        <h2 class="text-light pt-5">Activities</h2>
        <div class="row height-with-nav-activities">
            <div class="container">
                <div class="row align-items-center justify-content-center">
                        <div class="col d-flex align-items-center justify-content-center p-3 m-4 bg-activities-content flex-column border">
                            <h4>Riwayat Pendidikan</h4>
                            <hr>
                            <ol id="education" type="1">
                                <li>SDN Cikoko 03, 2007-2013</li>
                                <li>SMPN 73 Jakarta, 2013-2016</li>
                                <li>SMAN 8 Jakarta, 2016-2019</li>
                                <li>Universitas Indonesia, 2019-sekarang</li>
                            </ol>
                        </div>
                        <div class="col d-flex align-items-center justify-content-center p-3 m-4 bg-activities-content flex-column border">
                            <h4>Organisasi dan Kepanitiaan</h4>
                            <hr>
                            <ol id="organization" type="1">
                                <li>Tim BFC Kemasyarakatan, 2017-2018</li>
                                <li>Pesta Rakyat Komputer, 2020</li>
                                <li>Staf Departemen Sosial Masyarakat FUKI Fasilkom UI, 2020-sekarang</li>
                            </ol>
                        </div>
                </div>
            </div>
            <div class="container bg-activities-content border align-items-center justify-content-center mt-4">
                    <h4 class="text-center mt-4 mb-1">Skills</h4>
                <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-4 d-flex align-items-center p-0 m-0 bg-activities-content">
                    <div class="col">
                        <div class="card bg-activities-content border justify-content-center align-items-center mb-4">
                            <img src="{% static 'story4_app/photos/python.svg' %}" class="card-img-top p-2" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Python</h5>
                            <p class="card-text"> Materi kuliah semester 1. Saat ini belajar otodidak.</p>
                        </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card bg-activities-content border justify-content-center align-items-center mb-4">
                        <img src="{% static 'story4_app/photos/java.svg' %}" class="card-img-top p-2" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Java</h5>
                            <p class="card-text"> Materi kuliah semester 2. Saat ini belajar otodidak.</p>
                        </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card bg-activities-content border justify-content-center align-items-center mb-4">
                        <img src="{% static 'story4_app/photos/germany.png' %}" class="card-img-top-flag p-2" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Bahasa jerman</h5>
                            <p class="card-text">Materi saat SMA. Saat ini belajar otodidak.</p>
                        </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card bg-activities-content border justify-content-center align-items-center mb-4">
                        <img src="{% static 'story4_app/photos/time.svg' %}" class="card-img-top-time p-2" alt="...">
                        <div class="card-body text-center">
                            <h5 class="card-title">Manajemen waktu</h5>
                            <p class="card-text">Pengalaman dari organisasi, kepanitiaan, dan seminar.</p>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <span class="custom-br bg-activities"></span>

    <div class="container-fluid background">
        <div id="contact"></div>
        <div class="row height-with-nav">
            <div class="col-lg-6 col-sm-23 h-lg-100 d-flex align-items-center justify-content-center">
                <h1 class="text-center">
                    Want to talk more with me?
                    Kindly contact me
                </h1>
            </div>
            <div class="col-lg-6 col-sm-23 h-lg-100 p-3 d-flex flex-column align-items-center justify-content-center">
                <div class="container">
                    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1">
                        <div class="col mb-5">
                            <a href="https://www.linkedin.com/in/taufiq-hadi-pratama-21b3b4192/" class="text-dark contact-text">
                                <img src="{% static 'story4_app/photos/linkedin.png' %}" class="img-contact">
                                Klik tulisan ini untuk melihat LinkedIn saya
                            </a>
                        </div>
                        <div class="col mb-5">
                            <a href="https://line.me/ti/p/r3BU2vFGwr" class="text-dark contact-text">
                                <img src="{% static 'story4_app/photos/line.svg' %}" class="img-contact">
                                Klik tulisan ini untuk melihat LINE saya
                            </a>
                        </div>
                        <div class="col mb-5">
                            <figure>
                                <img src="{% static 'story4_app/photos/email.svg' %}" class="img-contact email">
                                <figcaption class="email contact-text">taufiqhadipratama@gmail.com</figcaption>
                            </figure>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

story4_app/templates/story4_app/random.html
{% extends "story4_app/base.html" %}
{% block content %}
{% load static %}

    <div class="background container-fluid text-center">
        <span class="custom-br-random background"></span>
        <h3 class="text-center m-auto">Games that I like recently</h3>
        <span class="custom-br-random background"></span>
        <div class="row height-with-nav">
            <div class="col">
                <div class="col m=auto align-items-center justify-content-center text-center">
                    <h4>Genshin Impact</h4>
                    <h5>UID: 800556687 </h5>
                    <div class="row m-auto d-flex align-items-center justify-content-center">
                        <div class="col-lg-6 col-sm-23 h-lg-100 align-items-center justify-content-center d-flex flex-column pl-5">
                            <img src="{% static 'story4_app/photos/genshin.jpg' %}" class="img-fluid">
                        </div>
                        <div class="col-lg-6 col-sm-23 h-lg-100 d-flex flex-column p-5">
                            <h5>
                                Sebuah <i>open world</i> RPG yang membuat saya terpukau karena grafik
                                yang wow. Gamenya baru rilis 28 September lalu, masih baru sekali. Namun,
                                antusiasme para penyuka genre game ini sangat terlihat dari
                                <i>open beta test</i> yang sudah lalu. Saya sangat merekomendasikan
                                untuk orang-orang yang suka genre sejenis ini
                            </h5>
                        </div>
                    </div>
                </div>
                <span class="custom-br-random background"></span>
                <div class="col m=auto align-items-center justify-content-center text-center">
                    <h4>Honkai Impact 3</h4>
                    <h5>ID: 11445869</h5>
                    <div class="row row-cols-sm-2 m-auto d-flex align-items-center justify-content-center">
                        <div class="col-lg-6 col-sm-23 h-lg-100 d-flex flex-column align-items-center justify-content-center pl-5">
                            <img src="{% static 'story4_app/photos/honkai.jpg' %}" class="img-fluid">
                        </div>
                        <div class="col-lg-6 col-sm-23 h-lg-100 d-flex flex-column p-5">
                            <h5>
                                Rekomendasi dari temen SMA dulu, sampai sekarang masih gabosen mainnya.
                                Action RPG terbaik lah menurut saya. Dari dulu sampai sekarang targetnya
                                tetep sama, yaitu mengoleksi semua stigma dan weapon gacha.
                            </h5>
                        </div>
                    </div>
                </div>
                <span class="custom-br-random background"></span>
                <div class="col m=auto align-items-center justify-content-center text-center">
                    <h4>Arknights</h4>
                    <h5>Name: Trigonometri#2978</h5>
                    <div class="row row-cols-sm-2 m-auto d-flex align-items-center justify-content-center">
                        <div class="col-lg-6 col-sm-23 h-lg-100 d-flex flex-column align-items-center justify-content-center pl-5">
                            <img src="{% static 'story4_app/photos/arknights.jpg' %}" class="img-fluid">
                        </div>
                        <div class="col-lg-6 col-sm-23 h-lg-100 d-flex flex-column p-5">
                            <h5>
                                Awalnya gatau sama sekali dan gaminat terhadap game <i>tower defense</i>.
                                Namun, setelah nyoba, jadi ketagihan sendiri. Awalnya dikenalin dari
                                temen kuliah, namun setelah melihat level-level yang ditawarkan makin
                                sulit dan <i>event</i> yang semakin seru, jadilah ketagihan dengan game ini
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <span class="custom-br-random background"></span>
{% endblock %}